use_small_heuristics = "Max"                                                    
hard_tabs = true                                                                
max_width = 80                                                                  
use_field_init_shorthand = true                                                 
use_try_shorthand = true                                                        
edition = "2018"
